<?php

namespace Blog\tests\Integration;

use Blog\Database;
use Blog\LatestPosts;
use PHPUnit\Framework\TestCase;
use Blog\tests\Integration\ContainerProvider;

class LatestPostsTest extends TestCase
{
    private LatestPosts $latestPosts;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        require 'delete_latest_posts.php';
        require 'create_latest_posts.php';

        $container = ContainerProvider::getContainer();

        $this->latestPosts = new LatestPosts( $container->get( Database::class ) );




    }

    public function testGet() : void
    {
        $posts = $this->latestPosts->get( 7 );

//        var_dump( $posts ); exit;

        $testPost = null;

        foreach ( $posts as $post )
        {
            if ( $post[ 'title' ] === 'Test Post 1' )
            {
                $testPost = $post;
            }
        }

        $this->assertNotNull( $testPost );
        $this->assertEquals( 'test-post-1', $testPost[ 'url_key' ] );
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        require 'delete_latest_posts.php';
    }
}